# Generated by Django 4.2.2 on 2023-08-03 12:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ElectricityPrice",
        ),
    ]
